# Base configuration
baseURL = "https://webforsvqjug.github.io/"
languageCode        = "es-es"
title               = "SVQJUG Site"
theme               = "hello-friend-ng"

# Menu configuration
[menu]
    [[ menu.main]]
        identifier = "meetup"
        name = "Meetup"
        url = "https://www.meetup.com/SVQJUG/"
        weight = 1 
    [[menu.main]]
        identifier  = "code"
        name        = "Código de conducta"
        url         = "/code"
        weight = 2
    [[menu.main]]
        identifier  = "faq"
        name        = "FAQ"
        url         = "/faq"
        weight = 3
    [[menu.main]]
        identifier  = "resources"
        name        = "Recursos"
        url         = "/resources"
        weight = 4
    [[menu.main]]
        identifier  = "blog"
        name        = "Blog"
        url         = "/blog"
        weight = 5

# Params configuration
[params]
    homeSubtitle    = "Bienvenid@s a la web del SVQJUG"

[params.logo]
    logoText        = "$ cd /Inicio/"
    logoHomeLink    = "/"
    # Set to a valid CSS color to change the cursor in the logo.
    # logoColor     = "#67A2C9"

# Social icons
[[params.social]]
    name = "twitter"
    url  = "https://twitter.com/SVQJUG"

[[params.social]]
    name = "github"
    url  = "https://github.com/SVQJUG"
